name: Test Execution

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17        
      uses: actions/setup-java@v4 
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Maven Initialize     
      run: mvn initialize --file Engine/pom.xml
    - name: Maven Install        
      run: mvn install --file Engine/pom.xml
    - name: Set Permissions      
      run: chmod -R 755 ./
    - name: Run tests            
      run: ./Run.command -run -project_location "Projects/Azure DevOps" -release "Release1" -testset "Set1"
    - name: Upload Reports       
      uses: actions/upload-artifact@v4.3.6
      with:
        name: Execution Reports
        path: Projects/Azure DevOps/Results/TestExecution/Release1/Set1/Latest
